const groupList = [
  {
    id: 1,
    name: "Friends Reunion",
    message: "Hi Guys, Wassup!",
    time: "10:00 AM",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "React Developers",
    message: "React developers are the best!",
    time: "10:05 AM",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Node Developers",
    message: "Node developers are the best!",
    time: "10:10 AM",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Angular Developers",
    message: "Angular developers are the best!",
    time: "10:15 AM",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "Vue Developers",
    message: "Vue developers are the best!",
    time: "10:20 AM",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Python Developers",
    message: "Python developers are the best!",
    time: "10:25 AM",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "Java Developers",
    message: "Java developers are the best!",
    time: "10:30 AM",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "C++ Developers",
    message: "C++ developers are the best!",
    time: "10:35 AM",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Ruby Developers",
    message: "Ruby developers are the best!",
    time: "10:40 AM",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "PHP Developers",
    message: "PHP developers are the best!",
    time: "10:45 AM",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    name: "Swift Developers",
    message: "Swift developers are the best!",
    time: "10:50 AM",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    name: "Kotlin Developers",
    message: "Kotlin developers are the best!",
    time: "10:55 AM",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    name: "Go Developers",
    message: "Go developers are the best!",
    time: "11:00 AM",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    name: "Rust Developers",
    message: "Rust developers are the best!",
    time: "11:05 AM",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    name: "TypeScript Developers",
    message: "TypeScript developers are the best!",
    time: "11:10 AM",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
  },
];

export { groupList };
