const friendList = [
  {
    id: 1,
    name: "John Smith",
    message: "Hey guys, let's catch up this weekend!",
    time: "10:00 AM",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Emily Johnson",
    message: "Just finished my React project! So excited! 🎉",
    time: "10:05 AM",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Michael Davis",
    message: "Anyone up for a quick Node.js debugging session?",
    time: "10:10 AM",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Sophia Brown",
    message: "Angular is giving me a headache today 😵‍💫",
    time: "10:15 AM",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "David Wilson",
    message: "Vue is just so elegant, love working with it! 😍",
    time: "10:20 AM",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Olivia Martinez",
    message: "Python automation saved me HOURS today! 😁",
    time: "10:25 AM",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "James Anderson",
    message: "Java still rules the enterprise world! 💼",
    time: "10:30 AM",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Ava Thomas",
    message: "C++ might be old, but it's still powerful 💪",
    time: "10:35 AM",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Benjamin White",
    message: "Ruby on Rails is just so smooth! 🔥",
    time: "10:40 AM",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Charlotte Hall",
    message: "PHP may not be trendy, but it gets the job done! 😉",
    time: "10:45 AM",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    name: "William Scott",
    message: "Just built my first iOS app with Swift! So excited! 📱",
    time: "10:50 AM",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    name: "Mia Young",
    message: "Kotlin is making Android development so much easier!",
    time: "10:55 AM",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    name: "Daniel Harris",
    message: "Go is crazy fast! Loving it so far 🚀",
    time: "11:00 AM",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    name: "Ella Walker",
    message: "Rust is hard, but it’s worth learning for sure!",
    time: "11:05 AM",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    name: "Matthew Lewis",
    message: "TypeScript is a lifesaver for large projects! 🤓",
    time: "11:10 AM",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
  },
];

export { friendList };
const userList = [
    {
        id: 1,
        name: "John Smith",
        time: "10:00 AM",
        avatar: "https://randomuser.me/api/portraits/men/1.jpg",
        button: "+",
    },
    {
        id: 2,
        name: "Emily Johnson",
        time: "10:05 AM",
        avatar: "https://randomuser.me/api/portraits/women/2.jpg",
        button: "+",
    },
    {
        id: 3,
        name: "Michael Davis",
        time: "10:10 AM",
        avatar: "https://randomuser.me/api/portraits/men/3.jpg",
        button: "+",
    },
    {
        id: 4,
        name: "Sophia Brown",
        time: "10:15 AM",
        avatar: "https://randomuser.me/api/portraits/women/4.jpg",
        button: "+",
    },
    {
        id: 5,
        name: "David Wilson",
        time: "10:20 AM",
        avatar: "https://randomuser.me/api/portraits/men/5.jpg",
        button: "+",
    },
    {
        id: 6,
        name: "Olivia Martinez",
        time: "10:25 AM",
        avatar: "https://randomuser.me/api/portraits/women/6.jpg",
        button: "+",
    },
    {
        id: 7,
        name: "James Anderson",
        time: "10:30 AM",
        avatar: "https://randomuser.me/api/portraits/men/7.jpg",
        button: "+",
    },
    {
        id: 8,
        name: "Ava Thomas",
        time: "10:35 AM",
        avatar: "https://randomuser.me/api/portraits/women/8.jpg",
        button: "+",
    },
    {
        id: 9,
        name: "Benjamin White",
        time: "10:40 AM",
        avatar: "https://randomuser.me/api/portraits/men/9.jpg",
        button: "+",
    },
    {
        id: 10,
        name: "Charlotte Hall",
        time: "10:45 AM",
        avatar: "https://randomuser.me/api/portraits/women/10.jpg",
        button: "+",
    },
    {
        id: 11,
        name: "William Scott",
        time: "10:50 AM",
        avatar: "https://randomuser.me/api/portraits/men/11.jpg",
        button: "+",
    },
    {
        id: 12,
        name: "Mia Young",
        time: "10:55 AM",
        avatar: "https://randomuser.me/api/portraits/women/12.jpg",
        button: "+",
    },
    {
        id: 13,
        name: "Daniel Harris",
        time: "11:00 AM",
        avatar: "https://randomuser.me/api/portraits/men/13.jpg",
        button: "+",
    },
    {
        id: 14,
        name: "Ella Walker",
        time: "11:05 AM",
        avatar: "https://randomuser.me/api/portraits/women/14.jpg",
        button: "+",
    },
    {
        id: 15,
        name: "Matthew Lewis",
        time: "11:10 AM",
        avatar: "https://randomuser.me/api/portraits/men/15.jpg",
        button: "+",
    },
];
export { userList };
const groupList = [
    {
        id: 1,
        name: "Friends Reunion",
        message: "Hi Guys, Wassup!",
        avatar:
            "https://ui-avatars.com/api/?name=Friends+Reunion&background=random",
        button: "Join",
    },
    {
        id: 2,
        name: "React Developers",
        message: "React developers are the best!",
        avatar:
            "https://ui-avatars.com/api/?name=React+Developers&background=random",
        button: "Join",
    },
    {
        id: 3,
        name: "Node Developers",
        message: "Node developers are the best!",
        avatar:
            "https://ui-avatars.com/api/?name=Node+Developers&background=random",
        button: "Join",
    },
    {
        id: 4,
        name: "Angular Developers",
        message: "Angular developers are the best!",
        avatar:
            "https://ui-avatars.com/api/?name=Angular+Developers&background=random",
        button: "Join",
    },
    {
        id: 5,
        name: "Vue Developers",
        message: "Vue developers are the best!",
        avatar: "https://ui-avatars.com/api/?name=Vue+Developers&background=random",
        button: "Join",
    },
    {
        id: 6,
        name: "Python Developers",
        message: "Python developers are the best!",
        avatar:
            "https://ui-avatars.com/api/?name=Python+Developers&background=random",
        button: "Join",
    },
    {
        id: 7,
        name: "Java Developers",
        message: "Java developers are the best!",
        avatar:
            "https://ui-avatars.com/api/?name=Java+Developers&background=random",
        button: "Join",
    },
    {
        id: 8,
        name: "C++ Developers",
        message: "C++ developers are the best!",
        avatar: "https://ui-avatars.com/api/?name=C++Developers&background=random",
        button: "Join",
    },
    {
        id: 9,
        name: "Ruby Developers",
        message: "Ruby developers are the best!",
        avatar:
            "https://ui-avatars.com/api/?name=Ruby+Developers&background=random",
        button: "Join",
    },
    {
        id: 10,
        name: "PHP Developers",
        message: "PHP developers are the best!",
        avatar: "https://ui-avatars.com/api/?name=PHP+Developers&background=random",
        button: "Join",
    },
];

export { groupList };
